import type { Player, Joker } from './types';

// Calculate market value based on player attributes
function calculateMarketValue(player: Omit<Player, 'marketValue' | 'joker'>): number {
  const overall = player.baseOverall;
  const tier = player.marketTier;

  // Base value from overall rating
  let baseValue = Math.round((overall - 60) * 1.2);

  // Tier multiplier
  const tierMultipliers = {
    star: 1.5,
    high: 1.2,
    medium: 1.0,
    low: 0.8
  };

  baseValue = Math.round(baseValue * tierMultipliers[tier]);

  // Age factor (younger = slightly more valuable)
  if (player.age < 25) baseValue += 2;
  if (player.age > 32) baseValue -= 2;

  // Ensure minimum and maximum
  return Math.max(3, Math.min(baseValue, 50));
}

// Joker generation logic
function generateJoker(): Joker | undefined {
  // 20% chance for a player to have a joker
  if (Math.random() > 0.2) return undefined;

  const jokerTypes = [
    { type: 'budget' as const, weight: 40, valueRange: [5, 15] },
    { type: 'scout' as const, weight: 30, valueRange: [1, 2] },
    { type: 'buff' as const, weight: 20, valueRange: [1, 2] },
    { type: 'free_transfer' as const, weight: 10, valueRange: [5, 10] }
  ];

  // Weighted random selection
  const totalWeight = jokerTypes.reduce((sum, j) => sum + j.weight, 0);
  let random = Math.random() * totalWeight;

  for (const jokerType of jokerTypes) {
    random -= jokerType.weight;
    if (random <= 0) {
      const [min, max] = jokerType.valueRange;
      const value = Math.floor(Math.random() * (max - min + 1)) + min;
      return {
        type: jokerType.type,
        value,
        revealed: false
      };
    }
  }

  return undefined;
}

export const playerPool: Player[] = [
  {
    "id": "gk_001",
    "name": "Thibaut Courtois",
    "age": 34,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 90,
    "marketTier": "star",
    "archetype": "Refleks Uzmanı",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 45,
      "shooting": 25,
      "passing": 72,
      "dribbling": 55,
      "defending": 88,
      "physical": 85,
      "aerial": 92,
      "vision": 65,
      "stamina": 60,
      "composure": 88
    }
  },
  {
    "id": "gk_002",
    "name": "Jan Oblak",
    "age": 33,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 87,
    "marketTier": "high",
    "archetype": "Çizgi Kalecisi",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 40,
      "shooting": 20,
      "passing": 58,
      "dribbling": 48,
      "defending": 89,
      "physical": 82,
      "aerial": 85,
      "vision": 55,
      "stamina": 50,
      "composure": 86
    }
  },
  {
    "id": "gk_003",
    "name": "Alisson Becker",
    "age": 33,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 89,
    "marketTier": "star",
    "archetype": "Pasör Kaleci",
    "preferredRoles": ["Sweeper Keeper"],
    "attributes": {
      "pace": 55,
      "shooting": 20,
      "passing": 85,
      "dribbling": 58,
      "defending": 87,
      "physical": 80,
      "aerial": 82,
      "vision": 75,
      "stamina": 55,
      "composure": 88
    }
  },
  {
    "id": "gk_004",
    "name": "Ederson",
    "age": 33,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 88,
    "marketTier": "star",
    "archetype": "Libero Kaleci",
    "preferredRoles": ["Sweeper Keeper"],
    "attributes": {
      "pace": 58,
      "shooting": 25,
      "passing": 92,
      "dribbling": 62,
      "defending": 84,
      "physical": 78,
      "aerial": 76,
      "vision": 82,
      "stamina": 58,
      "composure": 86
    }
  },
  {
    "id": "gk_005",
    "name": "Gianluigi Donnarumma",
    "age": 27,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 89,
    "marketTier": "star",
    "archetype": "Çizgi Kalecisi",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 48,
      "shooting": 20,
      "passing": 70,
      "dribbling": 52,
      "defending": 90,
      "physical": 84,
      "aerial": 88,
      "vision": 60,
      "stamina": 58,
      "composure": 85
    }
  },
  {
    "id": "gk_006",
    "name": "Mike Maignan",
    "age": 31,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "Refleks Uzmanı",
    "preferredRoles": ["Goalkeeper", "Sweeper Keeper"],
    "attributes": {
      "pace": 52,
      "shooting": 28,
      "passing": 75,
      "dribbling": 58,
      "defending": 88,
      "physical": 80,
      "aerial": 82,
      "vision": 68,
      "stamina": 58,
      "composure": 83
    }
  },
  {
    "id": "gk_007",
    "name": "David Raya",
    "age": 30,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "Pasör Kaleci",
    "preferredRoles": ["Sweeper Keeper"],
    "attributes": {
      "pace": 50,
      "shooting": 22,
      "passing": 82,
      "dribbling": 55,
      "defending": 84,
      "physical": 75,
      "aerial": 80,
      "vision": 72,
      "stamina": 55,
      "composure": 82
    }
  },
  {
    "id": "gk_008",
    "name": "Emiliano Martínez",
    "age": 34,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Ortaya Hâkim Kaleci",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 48,
      "shooting": 25,
      "passing": 68,
      "dribbling": 52,
      "defending": 86,
      "physical": 84,
      "aerial": 88,
      "vision": 62,
      "stamina": 60,
      "composure": 92
    }
  },
  {
    "id": "gk_009",
    "name": "Uğurcan Çakır",
    "age": 30,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 82,
    "marketTier": "high",
    "archetype": "Çizgi Kalecisi",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 48,
      "shooting": 22,
      "passing": 68,
      "dribbling": 50,
      "defending": 83,
      "physical": 79,
      "aerial": 78,
      "vision": 60,
      "stamina": 58,
      "composure": 76
    }
  },
  {
    "id": "gk_010",
    "name": "Unai Simón",
    "age": 29,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 83,
    "marketTier": "high",
    "archetype": "Ortaya Hâkim Kaleci",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 48,
      "shooting": 20,
      "passing": 68,
      "dribbling": 50,
      "defending": 84,
      "physical": 76,
      "aerial": 82,
      "vision": 62,
      "stamina": 55,
      "composure": 80
    }
  },
  {
    "id": "gk_011",
    "name": "Guglielmo Vicario",
    "age": 29,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "Refleks Uzmanı",
    "preferredRoles": ["Goalkeeper", "Sweeper Keeper"],
    "attributes": {
      "pace": 52,
      "shooting": 20,
      "passing": 70,
      "dribbling": 55,
      "defending": 85,
      "physical": 76,
      "aerial": 80,
      "vision": 64,
      "stamina": 56,
      "composure": 80
    }
  },
  {
    "id": "gk_012",
    "name": "Jordan Pickford",
    "age": 32,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 81,
    "marketTier": "medium",
    "archetype": "Refleks Uzmanı",
    "preferredRoles": ["Goalkeeper", "Sweeper Keeper"],
    "attributes": {
      "pace": 52,
      "shooting": 22,
      "passing": 75,
      "dribbling": 52,
      "defending": 82,
      "physical": 74,
      "aerial": 70,
      "vision": 68,
      "stamina": 55,
      "composure": 78
    }
  },
  {
    "id": "gk_013",
    "name": "Altay Bayındır",
    "age": 28,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 76,
    "marketTier": "medium",
    "archetype": "Refleks Uzmanı",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 50,
      "shooting": 20,
      "passing": 65,
      "dribbling": 52,
      "defending": 77,
      "physical": 75,
      "aerial": 78,
      "vision": 55,
      "stamina": 55,
      "composure": 70
    }
  },
  {
    "id": "gk_014",
    "name": "Mert Günok",
    "age": 37,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 78,
    "marketTier": "medium",
    "archetype": "Çizgi Kalecisi",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 38,
      "shooting": 22,
      "passing": 70,
      "dribbling": 45,
      "defending": 80,
      "physical": 78,
      "aerial": 82,
      "vision": 65,
      "stamina": 50,
      "composure": 84
    }
  },
  {
    "id": "gk_015",
    "name": "Alex Remiro",
    "age": 31,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 81,
    "marketTier": "medium",
    "archetype": "Çizgi Kalecisi",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 45,
      "shooting": 18,
      "passing": 68,
      "dribbling": 50,
      "defending": 82,
      "physical": 74,
      "aerial": 78,
      "vision": 58,
      "stamina": 52,
      "composure": 76
    }
  },
  {
    "id": "gk_016",
    "name": "Dominik Livaković",
    "age": 31,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 81,
    "marketTier": "medium",
    "archetype": "Refleks Uzmanı",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 46,
      "shooting": 18,
      "passing": 62,
      "dribbling": 50,
      "defending": 84,
      "physical": 75,
      "aerial": 72,
      "vision": 58,
      "stamina": 55,
      "composure": 80
    }
  },
  {
    "id": "gk_017",
    "name": "Nick Pope",
    "age": 34,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 82,
    "marketTier": "medium",
    "archetype": "Ortaya Hâkim Kaleci",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 48,
      "shooting": 18,
      "passing": 60,
      "dribbling": 45,
      "defending": 85,
      "physical": 82,
      "aerial": 88,
      "vision": 55,
      "stamina": 50,
      "composure": 80
    }
  },
  {
    "id": "gk_019",
    "name": "Bilal Bayazıt",
    "age": 27,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 74,
    "marketTier": "medium",
    "archetype": "Refleks Uzmanı",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 48,
      "shooting": 18,
      "passing": 60,
      "dribbling": 45,
      "defending": 76,
      "physical": 70,
      "aerial": 72,
      "vision": 55,
      "stamina": 50,
      "composure": 70
    }
  },
  {
    "id": "gk_020",
    "name": "Günay Güvenç",
    "age": 35,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 74,
    "marketTier": "medium",
    "archetype": "Çizgi Kalecisi",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 42,
      "shooting": 18,
      "passing": 62,
      "dribbling": 45,
      "defending": 75,
      "physical": 70,
      "aerial": 72,
      "vision": 55,
      "stamina": 48,
      "composure": 72
    }
  },
  {
    "id": "gk_021",
    "name": "Berke Özer",
    "age": 26,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 74,
    "marketTier": "medium",
    "archetype": "Refleks Uzmanı",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 50,
      "shooting": 18,
      "passing": 62,
      "dribbling": 48,
      "defending": 75,
      "physical": 72,
      "aerial": 74,
      "vision": 55,
      "stamina": 52,
      "composure": 70
    }
  },
  {
    "id": "gk_022",
    "name": "Doğan Alemdar",
    "age": 23,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 73,
    "marketTier": "medium",
    "archetype": "Çizgi Kalecisi",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 45,
      "shooting": 16,
      "passing": 58,
      "dribbling": 42,
      "defending": 74,
      "physical": 72,
      "aerial": 74,
      "vision": 52,
      "stamina": 48,
      "composure": 68
    }
  },
  {
    "id": "gk_023",
    "name": "Erce Kardeşler",
    "age": 32,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 71,
    "marketTier": "low",
    "archetype": "Çizgi Kalecisi",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 42,
      "shooting": 18,
      "passing": 58,
      "dribbling": 45,
      "defending": 72,
      "physical": 68,
      "aerial": 70,
      "vision": 50,
      "stamina": 50,
      "composure": 65
    }
  },
  {
    "id": "gk_027",
    "name": "Mark Flekken",
    "age": 33,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 76,
    "marketTier": "low",
    "archetype": "Pasör Kaleci",
    "preferredRoles": ["Sweeper Keeper"],
    "attributes": {
      "pace": 48,
      "shooting": 20,
      "passing": 74,
      "dribbling": 52,
      "defending": 77,
      "physical": 75,
      "aerial": 76,
      "vision": 62,
      "stamina": 50,
      "composure": 72
    }
  },
  {
    "id": "gk_028",
    "name": "Sven Ulreich",
    "age": 38,
    "primaryPosition": "GK",
    "secondaryPositions": [],
    "baseOverall": 72,
    "marketTier": "low",
    "archetype": "Ortaya Hâkim Kaleci",
    "preferredRoles": ["Goalkeeper"],
    "attributes": {
      "pace": 38,
      "shooting": 22,
      "passing": 65,
      "dribbling": 40,
      "defending": 72,
      "physical": 74,
      "aerial": 70,
      "vision": 60,
      "stamina": 45,
      "composure": 74
    }
  },
  {
    "id": "def_001",
    "name": "Virgil van Dijk",
    "age": 35,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 89,
    "marketTier": "star",
    "archetype": "Hava Hâkimi",
    "preferredRoles": ["Ball Playing Defender", "Stopper"],
    "attributes": {
      "pace": 76,
      "shooting": 60,
      "passing": 78,
      "dribbling": 70,
      "defending": 91,
      "physical": 88,
      "aerial": 93,
      "vision": 75,
      "stamina": 82,
      "composure": 90
    }
  },
  {
    "id": "def_002",
    "name": "Rúben Dias",
    "age": 29,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 89,
    "marketTier": "star",
    "archetype": "Kesici Stoper",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 62,
      "shooting": 38,
      "passing": 68,
      "dribbling": 55,
      "defending": 92,
      "physical": 89,
      "aerial": 85,
      "vision": 60,
      "stamina": 84,
      "composure": 88
    }
  },
  {
    "id": "def_003",
    "name": "William Saliba",
    "age": 25,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 87,
    "marketTier": "star",
    "archetype": "Pasör Stoper",
    "preferredRoles": ["Ball Playing Defender"],
    "attributes": {
      "pace": 78,
      "shooting": 42,
      "passing": 76,
      "dribbling": 70,
      "defending": 88,
      "physical": 84,
      "aerial": 82,
      "vision": 72,
      "stamina": 80,
      "composure": 86
    }
  },
  {
    "id": "def_004",
    "name": "Achraf Hakimi",
    "age": 27,
    "primaryPosition": "RB",
    "secondaryPositions": ["RWB", "RM"],
    "baseOverall": 85,
    "marketTier": "star",
    "archetype": "Bindiren Bek",
    "preferredRoles": ["Attacking Fullback", "Wing Back"],
    "attributes": {
      "pace": 93,
      "shooting": 72,
      "passing": 78,
      "dribbling": 84,
      "defending": 75,
      "physical": 76,
      "aerial": 62,
      "vision": 76,
      "stamina": 92,
      "composure": 78
    }
  },
  {
    "id": "def_005",
    "name": "Theo Hernández",
    "age": 28,
    "primaryPosition": "LB",
    "secondaryPositions": ["LWB", "LM"],
    "baseOverall": 86,
    "marketTier": "star",
    "archetype": "Bindiren Bek",
    "preferredRoles": ["Attacking Fullback", "Wing Back"],
    "attributes": {
      "pace": 94,
      "shooting": 74,
      "passing": 78,
      "dribbling": 83,
      "defending": 78,
      "physical": 82,
      "aerial": 72,
      "vision": 75,
      "stamina": 92,
      "composure": 78
    }
  },
  {
    "id": "def_006",
    "name": "Marquinhos",
    "age": 32,
    "primaryPosition": "CB",
    "secondaryPositions": ["DM"],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "Kapatıcı Stoper",
    "preferredRoles": ["Cover", "Ball Playing Defender"],
    "attributes": {
      "pace": 75,
      "shooting": 55,
      "passing": 78,
      "dribbling": 72,
      "defending": 88,
      "physical": 78,
      "aerial": 84,
      "vision": 70,
      "stamina": 82,
      "composure": 88
    }
  },
  {
    "id": "def_007",
    "name": "Gabriel Magalhães",
    "age": 28,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Fiziksel Savunmacı",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 72,
      "shooting": 45,
      "passing": 68,
      "dribbling": 60,
      "defending": 86,
      "physical": 88,
      "aerial": 87,
      "vision": 64,
      "stamina": 80,
      "composure": 82
    }
  },
  {
    "id": "def_008",
    "name": "Éder Militão",
    "age": 28,
    "primaryPosition": "CB",
    "secondaryPositions": ["RB"],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "Kesici Stoper",
    "preferredRoles": ["Stopper", "Cover"],
    "attributes": {
      "pace": 83,
      "shooting": 50,
      "passing": 72,
      "dribbling": 70,
      "defending": 86,
      "physical": 84,
      "aerial": 85,
      "vision": 68,
      "stamina": 82,
      "composure": 80
    }
  },
  {
    "id": "def_009",
    "name": "Ronald Araújo",
    "age": 27,
    "primaryPosition": "CB",
    "secondaryPositions": ["RB"],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "Fiziksel Savunmacı",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 78,
      "shooting": 45,
      "passing": 65,
      "dribbling": 62,
      "defending": 87,
      "physical": 90,
      "aerial": 88,
      "vision": 60,
      "stamina": 80,
      "composure": 78
    }
  },
  {
    "id": "def_010",
    "name": "Ferdi Kadıoğlu",
    "age": 26,
    "primaryPosition": "LB",
    "secondaryPositions": ["RB", "CM", "LM"],
    "baseOverall": 83,
    "marketTier": "high",
    "archetype": "İç Koridor Beki",
    "preferredRoles": ["Inverted Fullback", "Wing Back"],
    "attributes": {
      "pace": 86,
      "shooting": 70,
      "passing": 82,
      "dribbling": 86,
      "defending": 75,
      "physical": 72,
      "aerial": 60,
      "vision": 80,
      "stamina": 93,
      "composure": 78
    }
  },
  {
    "id": "def_011",
    "name": "Federico Dimarco",
    "age": 28,
    "primaryPosition": "LWB",
    "secondaryPositions": ["LB", "LM"],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "Çizgi Kanat Beki",
    "preferredRoles": ["Wing Back", "Wide Midfielder"],
    "attributes": {
      "pace": 84,
      "shooting": 75,
      "passing": 86,
      "dribbling": 81,
      "defending": 74,
      "physical": 70,
      "aerial": 58,
      "vision": 84,
      "stamina": 90,
      "composure": 80
    }
  },
  {
    "id": "def_012",
    "name": "Jules Koundé",
    "age": 27,
    "primaryPosition": "RB",
    "secondaryPositions": ["CB"],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "Savunmacı Bek",
    "preferredRoles": ["Fullback", "Ball Playing Defender"],
    "attributes": {
      "pace": 82,
      "shooting": 50,
      "passing": 76,
      "dribbling": 78,
      "defending": 84,
      "physical": 78,
      "aerial": 82,
      "vision": 70,
      "stamina": 85,
      "composure": 80
    }
  },
  {
    "id": "def_013",
    "name": "Trent Alexander-Arnold",
    "age": 27,
    "primaryPosition": "RB",
    "secondaryPositions": ["CM", "RWB"],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "İç Koridor Beki",
    "preferredRoles": ["Inverted Fullback", "Playmaker"],
    "attributes": {
      "pace": 78,
      "shooting": 76,
      "passing": 92,
      "dribbling": 80,
      "defending": 72,
      "physical": 68,
      "aerial": 55,
      "vision": 90,
      "stamina": 88,
      "composure": 82
    }
  },
  {
    "id": "def_014",
    "name": "Alphonso Davies",
    "age": 25,
    "primaryPosition": "LB",
    "secondaryPositions": ["LWB", "LM"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Bindiren Bek",
    "preferredRoles": ["Wing Back", "Attacking Fullback"],
    "attributes": {
      "pace": 95,
      "shooting": 68,
      "passing": 76,
      "dribbling": 84,
      "defending": 75,
      "physical": 76,
      "aerial": 62,
      "vision": 74,
      "stamina": 88,
      "composure": 76
    }
  },
  {
    "id": "def_015",
    "name": "Alessandro Bastoni",
    "age": 27,
    "primaryPosition": "CB",
    "secondaryPositions": ["LB"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Pasör Stoper",
    "preferredRoles": ["Ball Playing Defender"],
    "attributes": {
      "pace": 74,
      "shooting": 48,
      "passing": 82,
      "dribbling": 75,
      "defending": 84,
      "physical": 80,
      "aerial": 78,
      "vision": 76,
      "stamina": 82,
      "composure": 84
    }
  },
  {
    "id": "def_016",
    "name": "Lisandro Martínez",
    "age": 28,
    "primaryPosition": "CB",
    "secondaryPositions": ["LB", "DM"],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "Pasör Stoper",
    "preferredRoles": ["Ball Playing Defender"],
    "attributes": {
      "pace": 70,
      "shooting": 55,
      "passing": 82,
      "dribbling": 76,
      "defending": 84,
      "physical": 80,
      "aerial": 72,
      "vision": 78,
      "stamina": 84,
      "composure": 86
    }
  },
  {
    "id": "def_017",
    "name": "Cristian Romero",
    "age": 28,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Kesici Stoper",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 74,
      "shooting": 48,
      "passing": 68,
      "dribbling": 65,
      "defending": 86,
      "physical": 88,
      "aerial": 84,
      "vision": 62,
      "stamina": 82,
      "composure": 78
    }
  },
  {
    "id": "def_018",
    "name": "Nico Schlotterbeck",
    "age": 26,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "Pasör Stoper",
    "preferredRoles": ["Ball Playing Defender", "Stopper"],
    "attributes": {
      "pace": 76,
      "shooting": 55,
      "passing": 78,
      "dribbling": 72,
      "defending": 84,
      "physical": 84,
      "aerial": 82,
      "vision": 72,
      "stamina": 80,
      "composure": 80
    }
  },
  {
    "id": "def_019",
    "name": "Merih Demiral",
    "age": 28,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 79,
    "marketTier": "medium",
    "archetype": "Kesici Stoper",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 74,
      "shooting": 42,
      "passing": 62,
      "dribbling": 58,
      "defending": 80,
      "physical": 86,
      "aerial": 85,
      "vision": 55,
      "stamina": 76,
      "composure": 74
    }
  },
  {
    "id": "def_020",
    "name": "Çağlar Söyüncü",
    "age": 30,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 78,
    "marketTier": "medium",
    "archetype": "Önde Savunan Stoper",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 72,
      "shooting": 45,
      "passing": 65,
      "dribbling": 60,
      "defending": 78,
      "physical": 82,
      "aerial": 78,
      "vision": 58,
      "stamina": 75,
      "composure": 74
    }
  },
  {
    "id": "def_021",
    "name": "Abdülkerim Bardakcı",
    "age": 32,
    "primaryPosition": "CB",
    "secondaryPositions": ["LB"],
    "baseOverall": 79,
    "marketTier": "medium",
    "archetype": "Pasör Stoper",
    "preferredRoles": ["Ball Playing Defender"],
    "attributes": {
      "pace": 68,
      "shooting": 55,
      "passing": 75,
      "dribbling": 68,
      "defending": 80,
      "physical": 85,
      "aerial": 84,
      "vision": 72,
      "stamina": 78,
      "composure": 75
    }
  },
  {
    "id": "def_022",
    "name": "Samet Akaydin",
    "age": 32,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 75,
    "marketTier": "medium",
    "archetype": "Hava Hâkimi",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 62,
      "shooting": 40,
      "passing": 60,
      "dribbling": 55,
      "defending": 76,
      "physical": 84,
      "aerial": 86,
      "vision": 52,
      "stamina": 72,
      "composure": 70
    }
  },
  {
    "id": "def_023",
    "name": "Zeki Çelik",
    "age": 29,
    "primaryPosition": "RB",
    "secondaryPositions": ["RWB"],
    "baseOverall": 76,
    "marketTier": "medium",
    "archetype": "Savunmacı Bek",
    "preferredRoles": ["Fullback"],
    "attributes": {
      "pace": 78,
      "shooting": 50,
      "passing": 70,
      "dribbling": 72,
      "defending": 75,
      "physical": 76,
      "aerial": 65,
      "vision": 68,
      "stamina": 85,
      "composure": 74
    }
  },
  {
    "id": "def_024",
    "name": "Eren Elmalı",
    "age": 26,
    "primaryPosition": "LB",
    "secondaryPositions": ["LWB"],
    "baseOverall": 75,
    "marketTier": "medium",
    "archetype": "Bindiren Bek",
    "preferredRoles": ["Wing Back"],
    "attributes": {
      "pace": 82,
      "shooting": 52,
      "passing": 68,
      "dribbling": 74,
      "defending": 72,
      "physical": 70,
      "aerial": 64,
      "vision": 66,
      "stamina": 86,
      "composure": 70
    }
  },
  {
    "id": "def_025",
    "name": "Ozan Kabak",
    "age": 26,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 76,
    "marketTier": "medium",
    "archetype": "Fiziksel Savunmacı",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 66,
      "shooting": 45,
      "passing": 65,
      "dribbling": 62,
      "defending": 76,
      "physical": 82,
      "aerial": 84,
      "vision": 60,
      "stamina": 72,
      "composure": 70
    }
  },
  {
    "id": "def_026",
    "name": "Kaan Ayhan",
    "age": 31,
    "primaryPosition": "CB",
    "secondaryPositions": ["RB", "DM"],
    "baseOverall": 76,
    "marketTier": "medium",
    "archetype": "Pasör Stoper",
    "preferredRoles": ["Ball Playing Defender", "Anchor"],
    "attributes": {
      "pace": 60,
      "shooting": 62,
      "passing": 76,
      "dribbling": 68,
      "defending": 76,
      "physical": 78,
      "aerial": 75,
      "vision": 74,
      "stamina": 75,
      "composure": 78
    }
  },
  {
    "id": "def_027",
    "name": "Harry Maguire",
    "age": 33,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 79,
    "marketTier": "medium",
    "archetype": "Hava Hâkimi",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 48,
      "shooting": 55,
      "passing": 70,
      "dribbling": 60,
      "defending": 80,
      "physical": 86,
      "aerial": 90,
      "vision": 65,
      "stamina": 72,
      "composure": 76
    }
  },
  {
    "id": "def_028",
    "name": "Dan Burn",
    "age": 34,
    "primaryPosition": "LB",
    "secondaryPositions": ["CB"],
    "baseOverall": 78,
    "marketTier": "medium",
    "archetype": "Savunmacı Bek",
    "preferredRoles": ["Fullback", "Stopper"],
    "attributes": {
      "pace": 60,
      "shooting": 45,
      "passing": 68,
      "dribbling": 62,
      "defending": 80,
      "physical": 88,
      "aerial": 90,
      "vision": 64,
      "stamina": 80,
      "composure": 78
    }
  },
  {
    "id": "def_029",
    "name": "James Tarkowski",
    "age": 33,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 79,
    "marketTier": "medium",
    "archetype": "Kesici Stoper",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 58,
      "shooting": 42,
      "passing": 62,
      "dribbling": 55,
      "defending": 81,
      "physical": 85,
      "aerial": 86,
      "vision": 58,
      "stamina": 78,
      "composure": 75
    }
  },
  {
    "id": "def_030",
    "name": "Ben White",
    "age": 28,
    "primaryPosition": "RB",
    "secondaryPositions": ["CB"],
    "baseOverall": 82,
    "marketTier": "medium",
    "archetype": "Pasör Stoper",
    "preferredRoles": ["Inverted Fullback", "Ball Playing Defender"],
    "attributes": {
      "pace": 76,
      "shooting": 52,
      "passing": 78,
      "dribbling": 74,
      "defending": 82,
      "physical": 76,
      "aerial": 75,
      "vision": 74,
      "stamina": 84,
      "composure": 80
    }
  },
  {
    "id": "def_031",
    "name": "Marc Cucurella",
    "age": 28,
    "primaryPosition": "LB",
    "secondaryPositions": ["LWB", "LM"],
    "baseOverall": 82,
    "marketTier": "medium",
    "archetype": "Bindiren Bek",
    "preferredRoles": ["Wing Back", "Inverted Fullback"],
    "attributes": {
      "pace": 83,
      "shooting": 55,
      "passing": 76,
      "dribbling": 78,
      "defending": 80,
      "physical": 74,
      "aerial": 60,
      "vision": 72,
      "stamina": 90,
      "composure": 78
    }
  },
  {
    "id": "def_032",
    "name": "Diogo Dalot",
    "age": 27,
    "primaryPosition": "RB",
    "secondaryPositions": ["LB", "RWB"],
    "baseOverall": 80,
    "marketTier": "medium",
    "archetype": "Bindiren Bek",
    "preferredRoles": ["Wing Back", "Fullback"],
    "attributes": {
      "pace": 82,
      "shooting": 62,
      "passing": 75,
      "dribbling": 78,
      "defending": 76,
      "physical": 75,
      "aerial": 68,
      "vision": 72,
      "stamina": 86,
      "composure": 74
    }
  },
  {
    "id": "def_033",
    "name": "Denzel Dumfries",
    "age": 30,
    "primaryPosition": "RWB",
    "secondaryPositions": ["RB", "RM"],
    "baseOverall": 81,
    "marketTier": "medium",
    "archetype": "Bindiren Bek",
    "preferredRoles": ["Wing Back"],
    "attributes": {
      "pace": 84,
      "shooting": 68,
      "passing": 72,
      "dribbling": 74,
      "defending": 76,
      "physical": 86,
      "aerial": 82,
      "vision": 68,
      "stamina": 90,
      "composure": 76
    }
  },
  {
    "id": "def_034",
    "name": "Davinson Sánchez",
    "age": 30,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 80,
    "marketTier": "medium",
    "archetype": "Fiziksel Savunmacı",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 80,
      "shooting": 45,
      "passing": 65,
      "dribbling": 62,
      "defending": 81,
      "physical": 86,
      "aerial": 84,
      "vision": 58,
      "stamina": 82,
      "composure": 72
    }
  },
  {
    "id": "def_035",
    "name": "Alexander Djiku",
    "age": 32,
    "primaryPosition": "CB",
    "secondaryPositions": ["DM"],
    "baseOverall": 78,
    "marketTier": "medium",
    "archetype": "Kapatıcı Stoper",
    "preferredRoles": ["Cover", "Stopper"],
    "attributes": {
      "pace": 72,
      "shooting": 45,
      "passing": 68,
      "dribbling": 62,
      "defending": 80,
      "physical": 82,
      "aerial": 78,
      "vision": 60,
      "stamina": 76,
      "composure": 75
    }
  },
  {
    "id": "def_037",
    "name": "Onur Bulut",
    "age": 32,
    "primaryPosition": "RB",
    "secondaryPositions": ["RWB", "RM"],
    "baseOverall": 73,
    "marketTier": "medium",
    "archetype": "Savunmacı Bek",
    "preferredRoles": ["Fullback"],
    "attributes": {
      "pace": 74,
      "shooting": 55,
      "passing": 68,
      "dribbling": 68,
      "defending": 72,
      "physical": 70,
      "aerial": 62,
      "vision": 64,
      "stamina": 80,
      "composure": 70
    }
  },
  {
    "id": "def_043",
    "name": "Serdar Saatçı",
    "age": 23,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 71,
    "marketTier": "low",
    "archetype": "Fiziksel Savunmacı",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 64,
      "shooting": 35,
      "passing": 58,
      "dribbling": 50,
      "defending": 72,
      "physical": 78,
      "aerial": 75,
      "vision": 52,
      "stamina": 68,
      "composure": 65
    }
  },
  {
    "id": "def_045",
    "name": "Yasin Özcan",
    "age": 20,
    "primaryPosition": "LB",
    "secondaryPositions": ["CB"],
    "baseOverall": 71,
    "marketTier": "low",
    "archetype": "Savunmacı Bek",
    "preferredRoles": ["Fullback"],
    "attributes": {
      "pace": 74,
      "shooting": 40,
      "passing": 64,
      "dribbling": 65,
      "defending": 70,
      "physical": 72,
      "aerial": 68,
      "vision": 60,
      "stamina": 75,
      "composure": 68
    }
  },
  {
    "id": "def_047",
    "name": "Arda Kızıldağ",
    "age": 27,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 70,
    "marketTier": "low",
    "archetype": "Fiziksel Savunmacı",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 62,
      "shooting": 35,
      "passing": 55,
      "dribbling": 50,
      "defending": 72,
      "physical": 76,
      "aerial": 78,
      "vision": 50,
      "stamina": 68,
      "composure": 64
    }
  },
  {
    "id": "def_048",
    "name": "Tayyip Talha Sanuç",
    "age": 26,
    "primaryPosition": "CB",
    "secondaryPositions": [],
    "baseOverall": 73,
    "marketTier": "low",
    "archetype": "Kesici Stoper",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 65,
      "shooting": 40,
      "passing": 60,
      "dribbling": 55,
      "defending": 74,
      "physical": 78,
      "aerial": 76,
      "vision": 55,
      "stamina": 70,
      "composure": 68
    }
  },
  {
    "id": "def_049",
    "name": "Veysel Sarı",
    "age": 38,
    "primaryPosition": "CB",
    "secondaryPositions": ["RB"],
    "baseOverall": 70,
    "marketTier": "low",
    "archetype": "Hava Hâkimi",
    "preferredRoles": ["Stopper"],
    "attributes": {
      "pace": 48,
      "shooting": 45,
      "passing": 58,
      "dribbling": 52,
      "defending": 72,
      "physical": 78,
      "aerial": 80,
      "vision": 58,
      "stamina": 58,
      "composure": 74
    }
  },
  {
    "id": "def_058",
    "name": "Luan Peres",
    "age": 32,
    "primaryPosition": "CB",
    "secondaryPositions": ["LB"],
    "baseOverall": 73,
    "marketTier": "low",
    "archetype": "Pasör Stoper",
    "preferredRoles": ["Ball Playing Defender", "Fullback"],
    "attributes": {
      "pace": 68,
      "shooting": 42,
      "passing": 68,
      "dribbling": 65,
      "defending": 74,
      "physical": 72,
      "aerial": 70,
      "vision": 64,
      "stamina": 70,
      "composure": 72
    }
  },
  {
    "id": "def_070",
    "name": "Cenk Özkacar",
    "age": 25,
    "primaryPosition": "CB",
    "secondaryPositions": ["LB"],
    "baseOverall": 72,
    "marketTier": "low",
    "archetype": "Önde Savunan Stoper",
    "preferredRoles": ["Stopper", "Fullback"],
    "attributes": {
      "pace": 66,
      "shooting": 40,
      "passing": 62,
      "dribbling": 58,
      "defending": 73,
      "physical": 76,
      "aerial": 76,
      "vision": 56,
      "stamina": 70,
      "composure": 68
    }
  },
  {
    "id": "mid_001",
    "name": "Rodri",
    "age": 30,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 91,
    "marketTier": "star",
    "archetype": "Regista",
    "preferredRoles": ["Deep Lying Playmaker", "Anchor"],
    "attributes": {
      "pace": 62,
      "shooting": 75,
      "passing": 92,
      "dribbling": 80,
      "defending": 87,
      "physical": 85,
      "aerial": 82,
      "vision": 90,
      "stamina": 93,
      "composure": 92
    }
  },
  {
    "id": "mid_002",
    "name": "Jude Bellingham",
    "age": 23,
    "primaryPosition": "CM",
    "secondaryPositions": ["AM"],
    "baseOverall": 90,
    "marketTier": "star",
    "archetype": "Box-to-box",
    "preferredRoles": ["Box to Box Midfielder", "Shadow Striker"],
    "attributes": {
      "pace": 82,
      "shooting": 85,
      "passing": 86,
      "dribbling": 88,
      "defending": 78,
      "physical": 85,
      "aerial": 75,
      "vision": 86,
      "stamina": 92,
      "composure": 90
    }
  },
  {
    "id": "mid_003",
    "name": "Kevin De Bruyne",
    "age": 35,
    "primaryPosition": "AM",
    "secondaryPositions": ["CM"],
    "baseOverall": 90,
    "marketTier": "star",
    "archetype": "Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker"],
    "attributes": {
      "pace": 70,
      "shooting": 85,
      "passing": 95,
      "dribbling": 86,
      "defending": 62,
      "physical": 75,
      "aerial": 60,
      "vision": 96,
      "stamina": 84,
      "composure": 89
    }
  },
  {
    "id": "mid_004",
    "name": "Federico Valverde",
    "age": 28,
    "primaryPosition": "CM",
    "secondaryPositions": ["RM", "RW", "DM"],
    "baseOverall": 88,
    "marketTier": "star",
    "archetype": "İki Yönlü Orta Saha",
    "preferredRoles": ["Box to Box Midfielder", "Carrilero"],
    "attributes": {
      "pace": 88,
      "shooting": 82,
      "passing": 85,
      "dribbling": 83,
      "defending": 80,
      "physical": 82,
      "aerial": 65,
      "vision": 82,
      "stamina": 96,
      "composure": 84
    }
  },
  {
    "id": "mid_005",
    "name": "Pedri",
    "age": 23,
    "primaryPosition": "CM",
    "secondaryPositions": ["AM"],
    "baseOverall": 86,
    "marketTier": "star",
    "archetype": "Yaratıcı Driplingçi",
    "preferredRoles": ["Advanced Playmaker", "Mezzala"],
    "attributes": {
      "pace": 76,
      "shooting": 68,
      "passing": 88,
      "dribbling": 89,
      "defending": 68,
      "physical": 64,
      "aerial": 50,
      "vision": 90,
      "stamina": 88,
      "composure": 86
    }
  },
  {
    "id": "mid_006",
    "name": "Florian Wirtz",
    "age": 23,
    "primaryPosition": "AM",
    "secondaryPositions": ["CM", "RW", "LW"],
    "baseOverall": 88,
    "marketTier": "star",
    "archetype": "Yaratıcı Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker", "Shadow Striker"],
    "attributes": {
      "pace": 82,
      "shooting": 80,
      "passing": 88,
      "dribbling": 91,
      "defending": 55,
      "physical": 64,
      "aerial": 52,
      "vision": 90,
      "stamina": 84,
      "composure": 86
    }
  },
  {
    "id": "mid_007",
    "name": "Jamal Musiala",
    "age": 23,
    "primaryPosition": "AM",
    "secondaryPositions": ["CM", "LW"],
    "baseOverall": 87,
    "marketTier": "star",
    "archetype": "Yaratıcı Driplingçi",
    "preferredRoles": ["Attacking Midfielder", "Inside Forward"],
    "attributes": {
      "pace": 83,
      "shooting": 78,
      "passing": 82,
      "dribbling": 92,
      "defending": 55,
      "physical": 62,
      "aerial": 52,
      "vision": 85,
      "stamina": 82,
      "composure": 84
    }
  },
  {
    "id": "mid_008",
    "name": "Martin Ødegaard",
    "age": 27,
    "primaryPosition": "AM",
    "secondaryPositions": ["CM"],
    "baseOverall": 87,
    "marketTier": "high",
    "archetype": "Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker"],
    "attributes": {
      "pace": 75,
      "shooting": 78,
      "passing": 90,
      "dribbling": 86,
      "defending": 65,
      "physical": 65,
      "aerial": 55,
      "vision": 92,
      "stamina": 88,
      "composure": 85
    }
  },
  {
    "id": "mid_009",
    "name": "Bruno Fernandes",
    "age": 31,
    "primaryPosition": "AM",
    "secondaryPositions": ["CM"],
    "baseOverall": 88,
    "marketTier": "high",
    "archetype": "Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker", "Shadow Striker"],
    "attributes": {
      "pace": 74,
      "shooting": 84,
      "passing": 90,
      "dribbling": 83,
      "defending": 68,
      "physical": 72,
      "aerial": 58,
      "vision": 92,
      "stamina": 92,
      "composure": 86
    }
  },
  {
    "id": "mid_010",
    "name": "Hakan Çalhanoğlu",
    "age": 32,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM", "AM"],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "Regista",
    "preferredRoles": ["Deep Lying Playmaker"],
    "attributes": {
      "pace": 66,
      "shooting": 84,
      "passing": 89,
      "dribbling": 82,
      "defending": 76,
      "physical": 70,
      "aerial": 55,
      "vision": 88,
      "stamina": 85,
      "composure": 84
    }
  },
  {
    "id": "mid_011",
    "name": "Arda Güler",
    "age": 21,
    "primaryPosition": "AM",
    "secondaryPositions": ["RM", "RW", "CM"],
    "baseOverall": 82,
    "marketTier": "high",
    "archetype": "Yaratıcı Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker", "Inside Forward"],
    "attributes": {
      "pace": 76,
      "shooting": 78,
      "passing": 85,
      "dribbling": 87,
      "defending": 50,
      "physical": 62,
      "aerial": 50,
      "vision": 86,
      "stamina": 74,
      "composure": 80
    }
  },
  {
    "id": "mid_012",
    "name": "Alexis Mac Allister",
    "age": 27,
    "primaryPosition": "CM",
    "secondaryPositions": ["DM", "AM"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "İki Yönlü Orta Saha",
    "preferredRoles": ["Deep Lying Playmaker", "Box to Box Midfielder"],
    "attributes": {
      "pace": 72,
      "shooting": 78,
      "passing": 86,
      "dribbling": 82,
      "defending": 78,
      "physical": 75,
      "aerial": 60,
      "vision": 86,
      "stamina": 88,
      "composure": 86
    }
  },
  {
    "id": "mid_013",
    "name": "Aurélien Tchouaméni",
    "age": 26,
    "primaryPosition": "DM",
    "secondaryPositions": ["CB", "CM"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Kesici Ön Libero",
    "preferredRoles": ["Anchor", "Ball Winning Midfielder"],
    "attributes": {
      "pace": 75,
      "shooting": 70,
      "passing": 82,
      "dribbling": 78,
      "defending": 85,
      "physical": 86,
      "aerial": 82,
      "vision": 80,
      "stamina": 88,
      "composure": 84
    }
  },
  {
    "id": "mid_014",
    "name": "Eduardo Camavinga",
    "age": 23,
    "primaryPosition": "CM",
    "secondaryPositions": ["DM", "LB"],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "İki Yönlü Orta Saha",
    "preferredRoles": ["Box to Box Midfielder", "Ball Winning Midfielder"],
    "attributes": {
      "pace": 80,
      "shooting": 72,
      "passing": 82,
      "dribbling": 84,
      "defending": 80,
      "physical": 78,
      "aerial": 68,
      "vision": 80,
      "stamina": 88,
      "composure": 82
    }
  },
  {
    "id": "mid_015",
    "name": "Gavi",
    "age": 22,
    "primaryPosition": "CM",
    "secondaryPositions": ["LW", "RW"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Mezzala",
    "preferredRoles": ["Mezzala", "Box to Box Midfielder"],
    "attributes": {
      "pace": 78,
      "shooting": 68,
      "passing": 82,
      "dribbling": 86,
      "defending": 72,
      "physical": 65,
      "aerial": 55,
      "vision": 84,
      "stamina": 90,
      "composure": 82
    }
  },
  {
    "id": "mid_016",
    "name": "Sandro Tonali",
    "age": 26,
    "primaryPosition": "CM",
    "secondaryPositions": ["DM"],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "Box-to-box",
    "preferredRoles": ["Box to Box Midfielder", "Deep Lying Playmaker"],
    "attributes": {
      "pace": 80,
      "shooting": 74,
      "passing": 83,
      "dribbling": 80,
      "defending": 80,
      "physical": 82,
      "aerial": 68,
      "vision": 82,
      "stamina": 90,
      "composure": 82
    }
  },
  {
    "id": "mid_017",
    "name": "Lucas Paquetá",
    "age": 29,
    "primaryPosition": "AM",
    "secondaryPositions": ["CM"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Yaratıcı Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker"],
    "attributes": {
      "pace": 74,
      "shooting": 78,
      "passing": 85,
      "dribbling": 88,
      "defending": 68,
      "physical": 78,
      "aerial": 70,
      "vision": 86,
      "stamina": 84,
      "composure": 84
    }
  },
  {
    "id": "mid_018",
    "name": "Teun Koopmeiners",
    "age": 28,
    "primaryPosition": "CM",
    "secondaryPositions": ["AM", "DM"],
    "baseOverall": 83,
    "marketTier": "high",
    "archetype": "Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker", "Box to Box Midfielder"],
    "attributes": {
      "pace": 72,
      "shooting": 80,
      "passing": 85,
      "dribbling": 78,
      "defending": 74,
      "physical": 80,
      "aerial": 72,
      "vision": 84,
      "stamina": 86,
      "composure": 82
    }
  },
  {
    "id": "mid_019",
    "name": "Orkun Kökçü",
    "age": 25,
    "primaryPosition": "CM",
    "secondaryPositions": ["AM", "DM"],
    "baseOverall": 82,
    "marketTier": "high",
    "archetype": "Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker", "Deep Lying Playmaker"],
    "attributes": {
      "pace": 72,
      "shooting": 78,
      "passing": 85,
      "dribbling": 80,
      "defending": 64,
      "physical": 68,
      "aerial": 55,
      "vision": 84,
      "stamina": 86,
      "composure": 80
    }
  },
  {
    "id": "mid_020",
    "name": "İsmail Yüksek",
    "age": 27,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 78,
    "marketTier": "medium",
    "archetype": "Kesici Ön Libero",
    "preferredRoles": ["Ball Winning Midfielder"],
    "attributes": {
      "pace": 74,
      "shooting": 62,
      "passing": 73,
      "dribbling": 75,
      "defending": 79,
      "physical": 80,
      "aerial": 70,
      "vision": 72,
      "stamina": 92,
      "composure": 72
    }
  },
  {
    "id": "mid_021",
    "name": "İrfan Can Kahveci",
    "age": 31,
    "primaryPosition": "RM",
    "secondaryPositions": ["AM", "CM", "RW"],
    "baseOverall": 80,
    "marketTier": "medium",
    "archetype": "İki Yönlü Orta Saha",
    "preferredRoles": ["Wide Playmaker", "Advanced Playmaker"],
    "attributes": {
      "pace": 72,
      "shooting": 83,
      "passing": 84,
      "dribbling": 85,
      "defending": 60,
      "physical": 72,
      "aerial": 65,
      "vision": 84,
      "stamina": 80,
      "composure": 81
    }
  },
  {
    "id": "mid_022",
    "name": "Salih Özcan",
    "age": 28,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 77,
    "marketTier": "medium",
    "archetype": "Kesici Ön Libero",
    "preferredRoles": ["Ball Winning Midfielder", "Anchor"],
    "attributes": {
      "pace": 70,
      "shooting": 60,
      "passing": 74,
      "dribbling": 72,
      "defending": 78,
      "physical": 82,
      "aerial": 70,
      "vision": 70,
      "stamina": 85,
      "composure": 74
    }
  },
  {
    "id": "mid_023",
    "name": "Kerem Demirbay",
    "age": 33,
    "primaryPosition": "CM",
    "secondaryPositions": ["DM", "AM"],
    "baseOverall": 78,
    "marketTier": "medium",
    "archetype": "İki Yönlü Orta Saha",
    "preferredRoles": ["Box to Box Midfielder", "Playmaker"],
    "attributes": {
      "pace": 62,
      "shooting": 76,
      "passing": 82,
      "dribbling": 78,
      "defending": 68,
      "physical": 70,
      "aerial": 60,
      "vision": 80,
      "stamina": 74,
      "composure": 76
    }
  },
  {
    "id": "mid_024",
    "name": "Salih Uçan",
    "age": 32,
    "primaryPosition": "CM",
    "secondaryPositions": ["DM", "AM"],
    "baseOverall": 75,
    "marketTier": "medium",
    "archetype": "Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker", "Deep Lying Playmaker"],
    "attributes": {
      "pace": 60,
      "shooting": 68,
      "passing": 78,
      "dribbling": 75,
      "defending": 64,
      "physical": 68,
      "aerial": 65,
      "vision": 78,
      "stamina": 72,
      "composure": 75
    }
  },
  {
    "id": "mid_025",
    "name": "Berkan Kutlu",
    "age": 28,
    "primaryPosition": "CM",
    "secondaryPositions": ["DM", "LB"],
    "baseOverall": 74,
    "marketTier": "medium",
    "archetype": "Box-to-box",
    "preferredRoles": ["Box to Box Midfielder"],
    "attributes": {
      "pace": 78,
      "shooting": 62,
      "passing": 72,
      "dribbling": 72,
      "defending": 70,
      "physical": 76,
      "aerial": 65,
      "vision": 68,
      "stamina": 92,
      "composure": 70
    }
  },
  {
    "id": "mid_026",
    "name": "Taylan Antalyalı",
    "age": 31,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 73,
    "marketTier": "medium",
    "archetype": "Regista",
    "preferredRoles": ["Deep Lying Playmaker"],
    "attributes": {
      "pace": 65,
      "shooting": 62,
      "passing": 76,
      "dribbling": 70,
      "defending": 68,
      "physical": 70,
      "aerial": 60,
      "vision": 74,
      "stamina": 78,
      "composure": 72
    }
  },
  {
    "id": "mid_027",
    "name": "Yusuf Yazıcı",
    "age": 29,
    "primaryPosition": "AM",
    "secondaryPositions": ["ST", "RW"],
    "baseOverall": 77,
    "marketTier": "medium",
    "archetype": "Yaratıcı Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker", "Shadow Striker"],
    "attributes": {
      "pace": 68,
      "shooting": 78,
      "passing": 80,
      "dribbling": 78,
      "defending": 45,
      "physical": 72,
      "aerial": 65,
      "vision": 82,
      "stamina": 72,
      "composure": 74
    }
  },
  {
    "id": "mid_028",
    "name": "Can Uzun",
    "age": 20,
    "primaryPosition": "AM",
    "secondaryPositions": ["ST", "CM"],
    "baseOverall": 74,
    "marketTier": "medium",
    "archetype": "Yaratıcı Driplingçi",
    "preferredRoles": ["Advanced Playmaker", "Shadow Striker"],
    "attributes": {
      "pace": 76,
      "shooting": 74,
      "passing": 72,
      "dribbling": 78,
      "defending": 40,
      "physical": 64,
      "aerial": 58,
      "vision": 74,
      "stamina": 70,
      "composure": 72
    }
  },
  {
    "id": "mid_031",
    "name": "Sean Longstaff",
    "age": 28,
    "primaryPosition": "CM",
    "secondaryPositions": ["DM"],
    "baseOverall": 76,
    "marketTier": "medium",
    "archetype": "Box-to-box",
    "preferredRoles": ["Box to Box Midfielder"],
    "attributes": {
      "pace": 68,
      "shooting": 68,
      "passing": 75,
      "dribbling": 72,
      "defending": 74,
      "physical": 78,
      "aerial": 70,
      "vision": 72,
      "stamina": 88,
      "composure": 74
    }
  },
  {
    "id": "mid_035",
    "name": "Piotr Zieliński",
    "age": 32,
    "primaryPosition": "CM",
    "secondaryPositions": ["AM"],
    "baseOverall": 82,
    "marketTier": "medium",
    "archetype": "Mezzala",
    "preferredRoles": ["Mezzala", "Advanced Playmaker"],
    "attributes": {
      "pace": 76,
      "shooting": 78,
      "passing": 84,
      "dribbling": 85,
      "defending": 62,
      "physical": 66,
      "aerial": 55,
      "vision": 82,
      "stamina": 80,
      "composure": 80
    }
  },
  {
    "id": "mid_036",
    "name": "Mario Pašalić",
    "age": 31,
    "primaryPosition": "AM",
    "secondaryPositions": ["CM"],
    "baseOverall": 79,
    "marketTier": "medium",
    "archetype": "Box-to-box",
    "preferredRoles": ["Shadow Striker", "Box to Box Midfielder"],
    "attributes": {
      "pace": 70,
      "shooting": 78,
      "passing": 76,
      "dribbling": 75,
      "defending": 64,
      "physical": 76,
      "aerial": 78,
      "vision": 75,
      "stamina": 84,
      "composure": 78
    }
  },
  {
    "id": "mid_038",
    "name": "Fred",
    "age": 33,
    "primaryPosition": "CM",
    "secondaryPositions": ["DM"],
    "baseOverall": 80,
    "marketTier": "medium",
    "archetype": "Box-to-box",
    "preferredRoles": ["Box to Box Midfielder", "Ball Winning Midfielder"],
    "attributes": {
      "pace": 76,
      "shooting": 70,
      "passing": 78,
      "dribbling": 80,
      "defending": 76,
      "physical": 72,
      "aerial": 55,
      "vision": 78,
      "stamina": 92,
      "composure": 78
    }
  },
  {
    "id": "mid_039",
    "name": "Lucas Torreira",
    "age": 30,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 81,
    "marketTier": "medium",
    "archetype": "Kesici Ön Libero",
    "preferredRoles": ["Ball Winning Midfielder"],
    "attributes": {
      "pace": 72,
      "shooting": 65,
      "passing": 78,
      "dribbling": 76,
      "defending": 82,
      "physical": 75,
      "aerial": 50,
      "vision": 75,
      "stamina": 94,
      "composure": 80
    }
  },
  {
    "id": "mid_040",
    "name": "Gabriel Sara",
    "age": 27,
    "primaryPosition": "CM",
    "secondaryPositions": ["AM", "RM"],
    "baseOverall": 80,
    "marketTier": "medium",
    "archetype": "Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker", "Mezzala"],
    "attributes": {
      "pace": 74,
      "shooting": 78,
      "passing": 84,
      "dribbling": 82,
      "defending": 65,
      "physical": 70,
      "aerial": 60,
      "vision": 82,
      "stamina": 85,
      "composure": 78
    }
  },
  {
    "id": "mid_045",
    "name": "Mahmut Tekdemir",
    "age": 38,
    "primaryPosition": "DM",
    "secondaryPositions": ["CB", "CM"],
    "baseOverall": 70,
    "marketTier": "low",
    "archetype": "Kesici Ön Libero",
    "preferredRoles": ["Anchor", "Ball Winning Midfielder"],
    "attributes": {
      "pace": 52,
      "shooting": 55,
      "passing": 68,
      "dribbling": 62,
      "defending": 74,
      "physical": 72,
      "aerial": 68,
      "vision": 65,
      "stamina": 60,
      "composure": 72
    }
  },
  {
    "id": "mid_048",
    "name": "Tolga Ciğerci",
    "age": 34,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 72,
    "marketTier": "low",
    "archetype": "Box-to-box",
    "preferredRoles": ["Box to Box Midfielder"],
    "attributes": {
      "pace": 60,
      "shooting": 68,
      "passing": 72,
      "dribbling": 68,
      "defending": 70,
      "physical": 76,
      "aerial": 72,
      "vision": 70,
      "stamina": 88,
      "composure": 70
    }
  },
  {
    "id": "mid_051",
    "name": "Doğucan Haspolat",
    "age": 26,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 71,
    "marketTier": "low",
    "archetype": "Kesici Ön Libero",
    "preferredRoles": ["Ball Winning Midfielder"],
    "attributes": {
      "pace": 68,
      "shooting": 58,
      "passing": 68,
      "dribbling": 66,
      "defending": 71,
      "physical": 72,
      "aerial": 62,
      "vision": 64,
      "stamina": 78,
      "composure": 68
    }
  },
  {
    "id": "mid_052",
    "name": "Cihan Çanak",
    "age": 21,
    "primaryPosition": "AM",
    "secondaryPositions": ["RW", "LW"],
    "baseOverall": 70,
    "marketTier": "low",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward", "Advanced Playmaker"],
    "attributes": {
      "pace": 78,
      "shooting": 65,
      "passing": 68,
      "dribbling": 75,
      "defending": 38,
      "physical": 58,
      "aerial": 50,
      "vision": 66,
      "stamina": 65,
      "composure": 64
    }
  },
  {
    "id": "mid_053",
    "name": "Bartuğ Elmaz",
    "age": 23,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 70,
    "marketTier": "low",
    "archetype": "Regista",
    "preferredRoles": ["Deep Lying Playmaker"],
    "attributes": {
      "pace": 62,
      "shooting": 60,
      "passing": 76,
      "dribbling": 70,
      "defending": 62,
      "physical": 64,
      "aerial": 58,
      "vision": 78,
      "stamina": 70,
      "composure": 72
    }
  },
  {
    "id": "mid_054",
    "name": "Ege Tıknaz",
    "age": 22,
    "primaryPosition": "DM",
    "secondaryPositions": ["CM"],
    "baseOverall": 69,
    "marketTier": "low",
    "archetype": "Kesici Ön Libero",
    "preferredRoles": ["Ball Winning Midfielder", "Anchor"],
    "attributes": {
      "pace": 66,
      "shooting": 50,
      "passing": 66,
      "dribbling": 64,
      "defending": 68,
      "physical": 72,
      "aerial": 65,
      "vision": 62,
      "stamina": 75,
      "composure": 66
    }
  },
  {
    "id": "mid_075",
    "name": "Samed Onur",
    "age": 24,
    "primaryPosition": "AM",
    "secondaryPositions": ["CM", "RW"],
    "baseOverall": 68,
    "marketTier": "low",
    "archetype": "Yaratıcı Oyun Kurucu",
    "preferredRoles": ["Advanced Playmaker"],
    "attributes": {
      "pace": 72,
      "shooting": 62,
      "passing": 70,
      "dribbling": 72,
      "defending": 42,
      "physical": 60,
      "aerial": 52,
      "vision": 70,
      "stamina": 66,
      "composure": 64
    }
  },
  {
    "id": "att_001",
    "name": "Kylian Mbappé",
    "age": 27,
    "primaryPosition": "ST",
    "secondaryPositions": ["LW", "RW"],
    "baseOverall": 92,
    "marketTier": "star",
    "archetype": "Hızlı Koşucu",
    "preferredRoles": ["Advanced Forward", "Inside Forward"],
    "attributes": {
      "pace": 97,
      "shooting": 90,
      "passing": 80,
      "dribbling": 93,
      "defending": 36,
      "physical": 78,
      "aerial": 70,
      "vision": 82,
      "stamina": 86,
      "composure": 88
    }
  },
  {
    "id": "att_002",
    "name": "Erling Haaland",
    "age": 26,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 91,
    "marketTier": "star",
    "archetype": "Ceza Sahası Bitiricisi",
    "preferredRoles": ["Poacher", "Target Man"],
    "attributes": {
      "pace": 89,
      "shooting": 94,
      "passing": 68,
      "dribbling": 78,
      "defending": 45,
      "physical": 90,
      "aerial": 85,
      "vision": 72,
      "stamina": 82,
      "composure": 90
    }
  },
  {
    "id": "att_003",
    "name": "Vinícius Júnior",
    "age": 26,
    "primaryPosition": "LW",
    "secondaryPositions": ["ST"],
    "baseOverall": 90,
    "marketTier": "star",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward", "Winger"],
    "attributes": {
      "pace": 95,
      "shooting": 84,
      "passing": 82,
      "dribbling": 94,
      "defending": 35,
      "physical": 68,
      "aerial": 55,
      "vision": 82,
      "stamina": 86,
      "composure": 85
    }
  },
  {
    "id": "att_004",
    "name": "Lamine Yamal",
    "age": 19,
    "primaryPosition": "RW",
    "secondaryPositions": ["RM", "AM"],
    "baseOverall": 84,
    "marketTier": "star",
    "archetype": "Yaratıcı Kanat",
    "preferredRoles": ["Winger", "Inside Forward"],
    "attributes": {
      "pace": 88,
      "shooting": 78,
      "passing": 82,
      "dribbling": 90,
      "defending": 40,
      "physical": 60,
      "aerial": 50,
      "vision": 84,
      "stamina": 76,
      "composure": 78
    }
  },
  {
    "id": "att_005",
    "name": "Harry Kane",
    "age": 33,
    "primaryPosition": "ST",
    "secondaryPositions": ["AM"],
    "baseOverall": 90,
    "marketTier": "star",
    "archetype": "Gezgin Forvet",
    "preferredRoles": ["Complete Forward", "Deep Lying Forward"],
    "attributes": {
      "pace": 68,
      "shooting": 93,
      "passing": 86,
      "dribbling": 82,
      "defending": 50,
      "physical": 84,
      "aerial": 85,
      "vision": 88,
      "stamina": 82,
      "composure": 92
    }
  },
  {
    "id": "att_006",
    "name": "Mohamed Salah",
    "age": 34,
    "primaryPosition": "RW",
    "secondaryPositions": ["ST"],
    "baseOverall": 89,
    "marketTier": "star",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward"],
    "attributes": {
      "pace": 88,
      "shooting": 88,
      "passing": 82,
      "dribbling": 88,
      "defending": 45,
      "physical": 76,
      "aerial": 62,
      "vision": 84,
      "stamina": 84,
      "composure": 88
    }
  },
  {
    "id": "att_007",
    "name": "Lautaro Martínez",
    "age": 29,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 89,
    "marketTier": "star",
    "archetype": "Presçi Forvet",
    "preferredRoles": ["Pressing Forward", "Advanced Forward"],
    "attributes": {
      "pace": 84,
      "shooting": 88,
      "passing": 76,
      "dribbling": 86,
      "defending": 55,
      "physical": 82,
      "aerial": 80,
      "vision": 78,
      "stamina": 88,
      "composure": 86
    }
  },
  {
    "id": "att_008",
    "name": "Lionel Messi",
    "age": 39,
    "primaryPosition": "AM",
    "secondaryPositions": ["ST", "RW"],
    "baseOverall": 88,
    "marketTier": "star",
    "archetype": "Sahte Dokuz",
    "preferredRoles": ["False Nine", "Advanced Playmaker"],
    "attributes": {
      "pace": 68,
      "shooting": 89,
      "passing": 92,
      "dribbling": 92,
      "defending": 30,
      "physical": 60,
      "aerial": 55,
      "vision": 94,
      "stamina": 65,
      "composure": 94
    }
  },
  {
    "id": "att_009",
    "name": "Cristiano Ronaldo",
    "age": 41,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 86,
    "marketTier": "star",
    "archetype": "Ceza Sahası Bitiricisi",
    "preferredRoles": ["Poacher", "Target Man"],
    "attributes": {
      "pace": 72,
      "shooting": 92,
      "passing": 75,
      "dribbling": 78,
      "defending": 34,
      "physical": 78,
      "aerial": 90,
      "vision": 76,
      "stamina": 70,
      "composure": 92
    }
  },
  {
    "id": "att_010",
    "name": "Bukayo Saka",
    "age": 25,
    "primaryPosition": "RW",
    "secondaryPositions": ["RM", "RWB"],
    "baseOverall": 87,
    "marketTier": "high",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward", "Winger"],
    "attributes": {
      "pace": 86,
      "shooting": 82,
      "passing": 84,
      "dribbling": 88,
      "defending": 65,
      "physical": 74,
      "aerial": 55,
      "vision": 84,
      "stamina": 88,
      "composure": 84
    }
  },
  {
    "id": "att_011",
    "name": "Rodrygo",
    "age": 25,
    "primaryPosition": "RW",
    "secondaryPositions": ["LW", "ST"],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward", "Advanced Forward"],
    "attributes": {
      "pace": 88,
      "shooting": 82,
      "passing": 80,
      "dribbling": 88,
      "defending": 42,
      "physical": 66,
      "aerial": 60,
      "vision": 82,
      "stamina": 82,
      "composure": 86
    }
  },
  {
    "id": "att_012",
    "name": "Victor Osimhen",
    "age": 27,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 87,
    "marketTier": "high",
    "archetype": "Hızlı Koşucu",
    "preferredRoles": ["Advanced Forward"],
    "attributes": {
      "pace": 90,
      "shooting": 86,
      "passing": 68,
      "dribbling": 80,
      "defending": 42,
      "physical": 86,
      "aerial": 88,
      "vision": 70,
      "stamina": 84,
      "composure": 82
    }
  },
  {
    "id": "att_013",
    "name": "Rafael Leão",
    "age": 27,
    "primaryPosition": "LW",
    "secondaryPositions": ["ST"],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "Hızlı Koşucu",
    "preferredRoles": ["Inside Forward", "Winger"],
    "attributes": {
      "pace": 93,
      "shooting": 78,
      "passing": 76,
      "dribbling": 88,
      "defending": 30,
      "physical": 78,
      "aerial": 65,
      "vision": 75,
      "stamina": 76,
      "composure": 78
    }
  },
  {
    "id": "att_014",
    "name": "Khvicha Kvaratskhelia",
    "age": 25,
    "primaryPosition": "LW",
    "secondaryPositions": ["RW", "AM"],
    "baseOverall": 86,
    "marketTier": "high",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward", "Winger"],
    "attributes": {
      "pace": 88,
      "shooting": 80,
      "passing": 82,
      "dribbling": 92,
      "defending": 42,
      "physical": 70,
      "aerial": 55,
      "vision": 84,
      "stamina": 78,
      "composure": 80
    }
  },
  {
    "id": "att_015",
    "name": "Kenan Yıldız",
    "age": 21,
    "primaryPosition": "LW",
    "secondaryPositions": ["ST", "AM"],
    "baseOverall": 81,
    "marketTier": "high",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward", "Advanced Forward"],
    "attributes": {
      "pace": 84,
      "shooting": 78,
      "passing": 74,
      "dribbling": 86,
      "defending": 40,
      "physical": 72,
      "aerial": 65,
      "vision": 76,
      "stamina": 76,
      "composure": 78
    }
  },
  {
    "id": "att_016",
    "name": "Kerem Aktürkoğlu",
    "age": 27,
    "primaryPosition": "LW",
    "secondaryPositions": ["RW", "AM"],
    "baseOverall": 81,
    "marketTier": "high",
    "archetype": "Hızlı Kontra Kanadı",
    "preferredRoles": ["Inside Forward", "Winger"],
    "attributes": {
      "pace": 88,
      "shooting": 76,
      "passing": 75,
      "dribbling": 82,
      "defending": 45,
      "physical": 65,
      "aerial": 55,
      "vision": 78,
      "stamina": 86,
      "composure": 74
    }
  },
  {
    "id": "att_017",
    "name": "Barış Alper Yılmaz",
    "age": 26,
    "primaryPosition": "RW",
    "secondaryPositions": ["ST", "RWB"],
    "baseOverall": 80,
    "marketTier": "high",
    "archetype": "Hızlı Kontra Kanadı",
    "preferredRoles": ["Winger", "Inside Forward"],
    "attributes": {
      "pace": 91,
      "shooting": 76,
      "passing": 72,
      "dribbling": 81,
      "defending": 62,
      "physical": 88,
      "aerial": 75,
      "vision": 70,
      "stamina": 93,
      "composure": 74
    }
  },
  {
    "id": "att_018",
    "name": "Semih Kılıçsoy",
    "age": 21,
    "primaryPosition": "ST",
    "secondaryPositions": ["LW", "RW"],
    "baseOverall": 79,
    "marketTier": "high",
    "archetype": "Presçi Forvet",
    "preferredRoles": ["Advanced Forward", "Inside Forward"],
    "attributes": {
      "pace": 85,
      "shooting": 80,
      "passing": 68,
      "dribbling": 82,
      "defending": 45,
      "physical": 82,
      "aerial": 70,
      "vision": 65,
      "stamina": 82,
      "composure": 75
    }
  },
  {
    "id": "att_019",
    "name": "Alexander Isak",
    "age": 26,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Gezgin Forvet",
    "preferredRoles": ["Advanced Forward", "Complete Forward"],
    "attributes": {
      "pace": 88,
      "shooting": 84,
      "passing": 74,
      "dribbling": 85,
      "defending": 40,
      "physical": 76,
      "aerial": 78,
      "vision": 72,
      "stamina": 80,
      "composure": 82
    }
  },
  {
    "id": "att_020",
    "name": "Ousmane Dembélé",
    "age": 29,
    "primaryPosition": "RW",
    "secondaryPositions": ["LW"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Yaratıcı Kanat",
    "preferredRoles": ["Winger", "Inside Forward"],
    "attributes": {
      "pace": 93,
      "shooting": 76,
      "passing": 80,
      "dribbling": 89,
      "defending": 35,
      "physical": 60,
      "aerial": 50,
      "vision": 82,
      "stamina": 75,
      "composure": 74
    }
  },
  {
    "id": "att_021",
    "name": "Julian Alvarez",
    "age": 26,
    "primaryPosition": "ST",
    "secondaryPositions": ["AM", "RW"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Presçi Forvet",
    "preferredRoles": ["Pressing Forward", "Shadow Striker"],
    "attributes": {
      "pace": 84,
      "shooting": 84,
      "passing": 78,
      "dribbling": 84,
      "defending": 60,
      "physical": 75,
      "aerial": 68,
      "vision": 80,
      "stamina": 90,
      "composure": 82
    }
  },
  {
    "id": "att_022",
    "name": "Gabriel Martinelli",
    "age": 25,
    "primaryPosition": "LW",
    "secondaryPositions": ["ST"],
    "baseOverall": 84,
    "marketTier": "high",
    "archetype": "Hızlı Koşucu",
    "preferredRoles": ["Inside Forward", "Winger"],
    "attributes": {
      "pace": 91,
      "shooting": 78,
      "passing": 75,
      "dribbling": 85,
      "defending": 45,
      "physical": 72,
      "aerial": 62,
      "vision": 74,
      "stamina": 88,
      "composure": 76
    }
  },
  {
    "id": "att_023",
    "name": "Ollie Watkins",
    "age": 30,
    "primaryPosition": "ST",
    "secondaryPositions": ["LW"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Presçi Forvet",
    "preferredRoles": ["Pressing Forward", "Advanced Forward"],
    "attributes": {
      "pace": 86,
      "shooting": 83,
      "passing": 75,
      "dribbling": 80,
      "defending": 48,
      "physical": 80,
      "aerial": 76,
      "vision": 76,
      "stamina": 88,
      "composure": 82
    }
  },
  {
    "id": "att_024",
    "name": "Nico Williams",
    "age": 24,
    "primaryPosition": "LW",
    "secondaryPositions": ["RW"],
    "baseOverall": 85,
    "marketTier": "high",
    "archetype": "Hızlı Koşucu",
    "preferredRoles": ["Winger", "Inside Forward"],
    "attributes": {
      "pace": 94,
      "shooting": 76,
      "passing": 78,
      "dribbling": 88,
      "defending": 38,
      "physical": 68,
      "aerial": 55,
      "vision": 76,
      "stamina": 80,
      "composure": 78
    }
  },
  {
    "id": "att_025",
    "name": "Ciro Immobile",
    "age": 36,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 81,
    "marketTier": "medium",
    "archetype": "Ceza Sahası Bitiricisi",
    "preferredRoles": ["Poacher", "Advanced Forward"],
    "attributes": {
      "pace": 72,
      "shooting": 86,
      "passing": 68,
      "dribbling": 76,
      "defending": 42,
      "physical": 75,
      "aerial": 74,
      "vision": 65,
      "stamina": 70,
      "composure": 84
    }
  },
  {
    "id": "att_026",
    "name": "Edin Džeko",
    "age": 40,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 81,
    "marketTier": "medium",
    "archetype": "Duvar Santrfor",
    "preferredRoles": ["Target Man", "Complete Forward"],
    "attributes": {
      "pace": 52,
      "shooting": 84,
      "passing": 75,
      "dribbling": 72,
      "defending": 40,
      "physical": 82,
      "aerial": 88,
      "vision": 76,
      "stamina": 62,
      "composure": 86
    }
  },
  {
    "id": "att_027",
    "name": "Dušan Tadić",
    "age": 37,
    "primaryPosition": "LW",
    "secondaryPositions": ["AM", "RW"],
    "baseOverall": 81,
    "marketTier": "medium",
    "archetype": "Yaratıcı Kanat",
    "preferredRoles": ["Advanced Playmaker", "Inside Forward"],
    "attributes": {
      "pace": 60,
      "shooting": 76,
      "passing": 86,
      "dribbling": 82,
      "defending": 45,
      "physical": 70,
      "aerial": 58,
      "vision": 88,
      "stamina": 72,
      "composure": 84
    }
  },
  {
    "id": "att_028",
    "name": "Mauro Icardi",
    "age": 33,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 82,
    "marketTier": "medium",
    "archetype": "Ceza Sahası Bitiricisi",
    "preferredRoles": ["Poacher", "Target Man"],
    "attributes": {
      "pace": 68,
      "shooting": 87,
      "passing": 75,
      "dribbling": 78,
      "defending": 35,
      "physical": 76,
      "aerial": 84,
      "vision": 76,
      "stamina": 70,
      "composure": 88
    }
  },
  {
    "id": "att_029",
    "name": "Yunus Akgün",
    "age": 26,
    "primaryPosition": "RW",
    "secondaryPositions": ["AM", "LW"],
    "baseOverall": 76,
    "marketTier": "medium",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward", "Advanced Playmaker"],
    "attributes": {
      "pace": 82,
      "shooting": 72,
      "passing": 75,
      "dribbling": 80,
      "defending": 48,
      "physical": 62,
      "aerial": 52,
      "vision": 74,
      "stamina": 76,
      "composure": 72
    }
  },
  {
    "id": "att_030",
    "name": "Cengiz Ünder",
    "age": 29,
    "primaryPosition": "RW",
    "secondaryPositions": ["RM"],
    "baseOverall": 76,
    "marketTier": "medium",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward"],
    "attributes": {
      "pace": 80,
      "shooting": 78,
      "passing": 74,
      "dribbling": 82,
      "defending": 40,
      "physical": 65,
      "aerial": 50,
      "vision": 72,
      "stamina": 68,
      "composure": 74
    }
  },
  {
    "id": "att_031",
    "name": "Ahmed Kutucu",
    "age": 26,
    "primaryPosition": "ST",
    "secondaryPositions": ["LW", "RW"],
    "baseOverall": 75,
    "marketTier": "medium",
    "archetype": "Geçiş Oyuncusu",
    "preferredRoles": ["Inside Forward", "Advanced Forward"],
    "attributes": {
      "pace": 80,
      "shooting": 75,
      "passing": 68,
      "dribbling": 76,
      "defending": 45,
      "physical": 74,
      "aerial": 68,
      "vision": 68,
      "stamina": 78,
      "composure": 72
    }
  },
  {
    "id": "att_034",
    "name": "Wout Weghorst",
    "age": 34,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 78,
    "marketTier": "medium",
    "archetype": "Duvar Santrfor",
    "preferredRoles": ["Target Man", "Pressing Forward"],
    "attributes": {
      "pace": 55,
      "shooting": 78,
      "passing": 68,
      "dribbling": 65,
      "defending": 55,
      "physical": 86,
      "aerial": 88,
      "vision": 68,
      "stamina": 84,
      "composure": 78
    }
  },
  {
    "id": "att_047",
    "name": "Cenk Tosun",
    "age": 35,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 74,
    "marketTier": "medium",
    "archetype": "Ceza Sahası Bitiricisi",
    "preferredRoles": ["Poacher", "Target Man"],
    "attributes": {
      "pace": 60,
      "shooting": 78,
      "passing": 65,
      "dribbling": 68,
      "defending": 38,
      "physical": 75,
      "aerial": 78,
      "vision": 66,
      "stamina": 64,
      "composure": 80
    }
  },
  {
    "id": "att_048",
    "name": "Umut Nayir",
    "age": 33,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 74,
    "marketTier": "medium",
    "archetype": "Hava Topları Uzmanı",
    "preferredRoles": ["Target Man"],
    "attributes": {
      "pace": 62,
      "shooting": 74,
      "passing": 58,
      "dribbling": 64,
      "defending": 45,
      "physical": 82,
      "aerial": 86,
      "vision": 55,
      "stamina": 72,
      "composure": 72
    }
  },
  {
    "id": "att_049",
    "name": "Halil Dervişoğlu",
    "age": 26,
    "primaryPosition": "ST",
    "secondaryPositions": ["LW", "AM"],
    "baseOverall": 72,
    "marketTier": "medium",
    "archetype": "Gezgin Forvet",
    "preferredRoles": ["Deep Lying Forward", "Inside Forward"],
    "attributes": {
      "pace": 76,
      "shooting": 70,
      "passing": 70,
      "dribbling": 78,
      "defending": 35,
      "physical": 64,
      "aerial": 60,
      "vision": 72,
      "stamina": 70,
      "composure": 68
    }
  },
  {
    "id": "att_050",
    "name": "Emre Mor",
    "age": 29,
    "primaryPosition": "RW",
    "secondaryPositions": ["RM", "LW"],
    "baseOverall": 73,
    "marketTier": "low",
    "archetype": "Yaratıcı Driplingçi",
    "preferredRoles": ["Winger", "Inside Forward"],
    "attributes": {
      "pace": 84,
      "shooting": 68,
      "passing": 70,
      "dribbling": 85,
      "defending": 35,
      "physical": 55,
      "aerial": 45,
      "vision": 70,
      "stamina": 64,
      "composure": 65
    }
  },
  {
    "id": "att_051",
    "name": "Serdar Dursun",
    "age": 34,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 73,
    "marketTier": "low",
    "archetype": "Hava Topları Uzmanı",
    "preferredRoles": ["Target Man"],
    "attributes": {
      "pace": 58,
      "shooting": 75,
      "passing": 62,
      "dribbling": 65,
      "defending": 35,
      "physical": 80,
      "aerial": 84,
      "vision": 60,
      "stamina": 68,
      "composure": 74
    }
  },
  {
    "id": "att_052",
    "name": "Oğulcan Çağlayan",
    "age": 30,
    "primaryPosition": "ST",
    "secondaryPositions": ["RW"],
    "baseOverall": 70,
    "marketTier": "low",
    "archetype": "Duvar Santrfor",
    "preferredRoles": ["Target Man", "Advanced Forward"],
    "attributes": {
      "pace": 70,
      "shooting": 68,
      "passing": 62,
      "dribbling": 66,
      "defending": 40,
      "physical": 76,
      "aerial": 74,
      "vision": 58,
      "stamina": 70,
      "composure": 66
    }
  },
  {
    "id": "att_053",
    "name": "Mustafa Hekimoğlu",
    "age": 19,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 69,
    "marketTier": "low",
    "archetype": "Hızlı Koşucu",
    "preferredRoles": ["Advanced Forward"],
    "attributes": {
      "pace": 78,
      "shooting": 68,
      "passing": 58,
      "dribbling": 70,
      "defending": 35,
      "physical": 66,
      "aerial": 65,
      "vision": 55,
      "stamina": 68,
      "composure": 64
    }
  },
  {
    "id": "att_055",
    "name": "Enes Destan",
    "age": 24,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 72,
    "marketTier": "low",
    "archetype": "Duvar Santrfor",
    "preferredRoles": ["Target Man", "Advanced Forward"],
    "attributes": {
      "pace": 75,
      "shooting": 72,
      "passing": 60,
      "dribbling": 68,
      "defending": 40,
      "physical": 78,
      "aerial": 76,
      "vision": 58,
      "stamina": 74,
      "composure": 68
    }
  },
  {
    "id": "att_056",
    "name": "Poyraz Efe Yıldırım",
    "age": 21,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 68,
    "marketTier": "low",
    "archetype": "Ceza Sahası Bitiricisi",
    "preferredRoles": ["Poacher"],
    "attributes": {
      "pace": 72,
      "shooting": 70,
      "passing": 55,
      "dribbling": 65,
      "defending": 32,
      "physical": 70,
      "aerial": 72,
      "vision": 52,
      "stamina": 66,
      "composure": 66
    }
  },
  {
    "id": "att_057",
    "name": "Mame Thiam",
    "age": 33,
    "primaryPosition": "ST",
    "secondaryPositions": ["LW"],
    "baseOverall": 74,
    "marketTier": "low",
    "archetype": "Duvar Santrfor",
    "preferredRoles": ["Target Man", "Inside Forward"],
    "attributes": {
      "pace": 75,
      "shooting": 74,
      "passing": 64,
      "dribbling": 72,
      "defending": 42,
      "physical": 80,
      "aerial": 78,
      "vision": 62,
      "stamina": 76,
      "composure": 72
    }
  },
  {
    "id": "att_058",
    "name": "Ali Sowe",
    "age": 32,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 72,
    "marketTier": "low",
    "archetype": "Duvar Santrfor",
    "preferredRoles": ["Target Man"],
    "attributes": {
      "pace": 74,
      "shooting": 70,
      "passing": 60,
      "dribbling": 68,
      "defending": 38,
      "physical": 82,
      "aerial": 76,
      "vision": 58,
      "stamina": 74,
      "composure": 68
    }
  },
  {
    "id": "att_059",
    "name": "Gökhan Töre",
    "age": 34,
    "primaryPosition": "RW",
    "secondaryPositions": ["LW", "AM"],
    "baseOverall": 69,
    "marketTier": "low",
    "archetype": "Yaratıcı Driplingçi",
    "preferredRoles": ["Winger"],
    "attributes": {
      "pace": 68,
      "shooting": 68,
      "passing": 70,
      "dribbling": 78,
      "defending": 35,
      "physical": 66,
      "aerial": 50,
      "vision": 70,
      "stamina": 58,
      "composure": 70
    }
  },
  {
    "id": "att_069",
    "name": "Bafetimbi Gomis",
    "age": 41,
    "primaryPosition": "ST",
    "secondaryPositions": [],
    "baseOverall": 70,
    "marketTier": "low",
    "archetype": "Ceza Sahası Bitiricisi",
    "preferredRoles": ["Poacher", "Target Man"],
    "attributes": {
      "pace": 50,
      "shooting": 78,
      "passing": 55,
      "dribbling": 62,
      "defending": 30,
      "physical": 82,
      "aerial": 76,
      "vision": 55,
      "stamina": 50,
      "composure": 76
    }
  },
  {
    "id": "att_075",
    "name": "Sinan Gümüş",
    "age": 32,
    "primaryPosition": "RW",
    "secondaryPositions": ["LW", "ST"],
    "baseOverall": 68,
    "marketTier": "low",
    "archetype": "İçe Kat Eden Kanat",
    "preferredRoles": ["Inside Forward"],
    "attributes": {
      "pace": 75,
      "shooting": 70,
      "passing": 65,
      "dribbling": 72,
      "defending": 35,
      "physical": 65,
      "aerial": 55,
      "vision": 62,
      "stamina": 60,
      "composure": 65
    }
  }
];

// Shuffle and return specified number of players
export function getShuffledPool(count: number = 100): Player[] {
  const shuffled = [...playerPool].sort(() => Math.random() - 0.5);
  const selected = shuffled.slice(0, count);

  // Assign jokers and calculate market values for selected players
  return selected.map(player => ({
    ...player,
    marketValue: calculateMarketValue(player),
    joker: generateJoker()
  }));
}
